Traceback (most recent call last):
  File "/home/lcur1624/ae_flow/data/chest_xray/get_data.py", line 1, in <module>
    import kaggle
  File "/home/lcur1624/.conda/envs/dl2022/lib/python3.10/site-packages/kaggle/__init__.py", line 23, in <module>
    api.authenticate()
  File "/home/lcur1624/.conda/envs/dl2022/lib/python3.10/site-packages/kaggle/api/kaggle_api_extended.py", line 164, in authenticate
    raise IOError('Could not find {}. Make sure it\'s located in'
OSError: Could not find kaggle.json. Make sure it's located in /home/lcur1624/.kaggle. Or use the environment method.
srun: error: r28n2: task 0: Exited with exit code 1
